name: Build project files

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: './smartblueberry'
      - run: |
          cd smartblueberry
          npm ci
          npm run frontend:build
          npm run backend:build
          git checkout -b build
          git add -f dist/**/*
          git config --global user.name "CI/CD"
          git config --global user.email "ci@github.com"
          git commit -m "update dist folder"
          git push origin build --force
