name: Build project files

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3
      - name: Build images
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --all \
            --target smartblueberry
