name: Build project files

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  init:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    outputs:
      architectures: ${{ steps.info.outputs.architectures }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master

  publish:
    name: Publish builder
    needs: init
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        architecture: ${{ fromJson(needs.init.outputs.architectures) }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish ${{ matrix.architecture }} builder
        uses: home-assistant/builder@master
        with:
          args: |
            --${{ matrix.architecture }} \
            --cosign \
            --target smartblueberry
